apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uzklmqrd2-python-gitops
  description: This is GitOps manifest for uzklmqrd2-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: uzklmqrd2-python
    backstage.io/kubernetes-id: uzklmqrd2-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uzklmqrd2-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uzklmqrd2-python
